[paths]
; แก้ path ด้านล่างให้ตรงกับเครื่องของคุณ
master_mc    = C:/Users/WICHARIT/Nan Yang Textile/SCM_Cloud - Knit Plan (AI)/MasterMC.xlsx
calendar     = C:/Users/WICHARIT/Nan Yang Textile/SCM_Cloud - Knit Plan (AI)/Calendar.xlsx
target_stock = C:/Users/WICHARIT/Nan Yang Textile/SCM_Cloud - Knit Plan (AI)/Target Stock MIN , MAX CORE GREIGE.xlsx
