[paths]
; แก้ path ด้านล่างให้ตรงกับเครื่องของคุณ
master_mc = C:/Users/WICHARIT/Nan Yang Textile/SCM_Cloud - Knit Plan (AI)/MasterMC.xlsx
calendar  = C:/Users/WICHARIT/Nan Yang Textile/SCM_Cloud - Knit Plan (AI)/Calendar.xlsx
